# NeON build file (http://github.com/c4s4/neon)

extends: c4s4/build/go-tool.yml

targets:

  run:
    doc: Run integration test
    steps:
    - script: 'failure = false'
    - try:
      - 'go run xspec-status.go test-result-ko.xml'
      - script: 'failure = true'
    - if: 'failure'
      then:
      - throw: 'Test failed'
    - 'go run xspec-status.go test-result-ok.xml'
